environment = "staging"

[http]

[http.certificates]

[http.certificates."sdkwork.com"]
certFile = "/opt/certs/letsencrypt/live/sdkwork.com/fullchain.pem"
certKeyFile = "/opt/certs/letsencrypt/live/sdkwork.com/privkey.pem"
chainFile = "/opt/certs/letsencrypt/live/sdkwork.com/chain.pem"
ocspStapling = true

[http.certificates."birdcoder.com"]
certFile = "/opt/certs/letsencrypt/live/birdcoder.com/fullchain.pem"
certKeyFile = "/opt/certs/letsencrypt/live/birdcoder.com/privkey.pem"
chainFile = "/opt/certs/letsencrypt/live/birdcoder.com/chain.pem"
ocspStapling = true

[http.certificates."dtupay.com"]
certFile = "/opt/certs/letsencrypt/live/dtupay.com/fullchain.pem"
certKeyFile = "/opt/certs/letsencrypt/live/dtupay.com/privkey.pem"
chainFile = "/opt/certs/letsencrypt/live/dtupay.com/chain.pem"
ocspStapling = true

[http.certificates."sdkwork.cn"]
certFile = "/opt/certs/letsencrypt/live/sdkwork.cn/fullchain.pem"
certKeyFile = "/opt/certs/letsencrypt/live/sdkwork.cn/privkey.pem"
chainFile = "/opt/certs/letsencrypt/live/sdkwork.cn/chain.pem"
ocspStapling = true

[http.certificates."birdcoder.cn"]
certFile = "/opt/certs/letsencrypt/live/birdcoder.cn/fullchain.pem"
certKeyFile = "/opt/certs/letsencrypt/live/birdcoder.cn/privkey.pem"
chainFile = "/opt/certs/letsencrypt/live/birdcoder.cn/chain.pem"
ocspStapling = true

[http.certificates."dtupay.cn"]
certFile = "/opt/certs/letsencrypt/live/dtupay.cn/fullchain.pem"
certKeyFile = "/opt/certs/letsencrypt/live/dtupay.cn/privkey.pem"
chainFile = "/opt/certs/letsencrypt/live/dtupay.cn/chain.pem"
ocspStapling = true

[[http.server]]
listen = ["80"]
serverName = ["tts-staging.sdkwork.com", "tts-staging.birdcoder.com", "tts-staging.dtupay.com", "tts-staging.sdkwork.cn", "tts-staging.birdcoder.cn", "tts-staging.dtupay.cn"]

[[http.server.location]]
match = "/api/"
proxyPass = "http://gateway"
proxyHttpVersion = "1.1"
proxySetHeader = ["Host $host", "X-Forwarded-For $proxy_add_x_forwarded_for", "X-Forwarded-Proto $scheme"]

[[http.server.location]]
match = "/"
proxyPass = "http://gateway"
proxyHttpVersion = "1.1"
proxySetHeader = ["Host $host", "X-Forwarded-For $proxy_add_x_forwarded_for", "X-Forwarded-Proto $scheme"]
proxyBuffering = false
proxyReadTimeout = "300s"

